server.port=8888
spring.application.name=gateway-service

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
spring.cloud.discovery.enabled=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Config Server
spring.cloud.config.enabled=false

# Gateway Routes
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Global CORS Configuration
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:3000
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

spring.cloud.gateway.routes[0].id=ms-auth
spring.cloud.gateway.routes[0].uri=lb://ms-auth
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/staff/**

spring.cloud.gateway.routes[1].id=ms-patient
spring.cloud.gateway.routes[1].uri=lb://ms-patient
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/patients/**

spring.cloud.gateway.routes[2].id=ms-planning
spring.cloud.gateway.routes[2].uri=lb://ms-planning
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/planning/**

spring.cloud.gateway.routes[3].id=ms-alert
spring.cloud.gateway.routes[3].uri=lb://ms-alert
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/alerts/**

spring.cloud.gateway.routes[4].id=ms-billing
spring.cloud.gateway.routes[4].uri=lb://ms-billing
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/billing/**



# Keycloak OAuth2 Client
# spring.security.oauth2.client.provider.keycloak.issuer-uri=${KEYCLOAK_URL:http://localhost:8080}/realms/meditrack-realm
# spring.security.oauth2.client.registration.keycloak.provider=keycloak
# spring.security.oauth2.client.registration.keycloak.client-id=meditrack-client
# spring.security.oauth2.client.registration.keycloak.client-secret=3kzuKaqH90cNcfUXp69UT7oFKdpKADNb
# spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
# spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
# spring.security.oauth2.client.registration.keycloak.scope=openid

# JWT Resource Server (API sécurisée)
# spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_URL:http://localhost:8080}/realms/meditrack-realm

# Actuator

