server.port=8081
spring.application.name=ms-auth
spring.cloud.config.enabled=true
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:9999/}

# spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_URL:http://localhost:9090}/realms/meditrack-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://meditrack-keycloak:9090/realms/meditrack-realm/protocol/openid-connect/certs
keycloak.realm=meditrack-realm
# keycloak.auth-server-url is likely used by Keycloak Admin Client bean if manually configured, or we need to add it
keycloak.auth-server-url=${KEYCLOAK_URL:http://localhost:9090}
keycloak.resource=meditrack-client
keycloak.credentials.secret=3SYHxXpFPLcNHipsPCKE0RXB88VcuUJG

eureka.instance.prefer-ip-address=true

# Actuator Configuration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.health.defaults.enabled=true

# Debug Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.example.msauth=DEBUG
logging.level.org.keycloak=DEBUG

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.datasource.url=jdbc:h2:mem:authdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


