server.port=8085
spring.application.name=ms-billing

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.datasource.url=jdbc:h2:mem:billingdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.cloud.config.enabled=true
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:9999/}

# spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_URL:http://localhost:8080}/realms/meditrack-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://meditrack-keycloak:9090/realms/meditrack-realm/protocol/openid-connect/certs
#keycloak.realm=meditrack-realm
#keycloak.server-url=${KEYCLOAK_URL:http://localhost:8080}
#keycloak.resource=meditrack-client
#keycloak.credentials.secret=3SYHxXpFPLcNHipsPCKE0RXB88VcuUJG

eureka.instance.prefer-ip-address=true

# Actuator Configuration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.health.defaults.enabled=true
